version: '3.7'
services:
  traefik:    
    image: traefik:v2.5.4
    ports:
      - "80:80"
    # - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.role==manager    
      labels:        
        - traefik.enable=true        
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public       
        - "traefik.http.middlewares.admin-auth.basicauth.users=admin:${HASHED_PASSWORD}"      
        - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.traefik-public-http.entrypoints=web
        - traefik.http.routers.traefik-public-http.middlewares=admin-auth           
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080          
        
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock:ro      
      - traefik-public-certificates:/certificates
    command:      
      - "--api.insecure=true"
      - "--providers.docker=true"     
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - "--providers.docker.exposedbydefault=false"
      - --providers.docker.swarmmode
      - --entrypoints.web.address=:80      
      - --accesslog
      - --log            
    networks:
      - traefik-public     

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true
