version: '3.7'
services:
    db:
      image: postgres:11-alpine
      environment:
        POSTGRES_DB: wiki
        POSTGRES_PASSWORD: xd123
        POSTGRES_USER: wiki
      logging:
        driver: "none"
      restart: unless-stopped
      networks:
        - wiki
      volumes:
        - db-data:/var/lib/postgresql/data
    app:    
      image: requarks/wiki:2.5.219      
      deploy:
        placement:
          constraints:
            - node.role==manager
        labels:        
          - traefik.enable=true        
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public                
          - traefik.http.routers.${NAME}-http.entrypoints=web
          - traefik.http.routers.${NAME}-http.rule=Host(`${DOMAIN}`)
          - traefik.http.services.${NAME}.loadbalancer.server.port=3000
      environment:
        DB_TYPE: postgres
        DB_HOST: wiki_db
        DB_PORT: 5432
        DB_USER: wiki
        DB_PASS: xd123
        DB_NAME: wiki
      restart: unless-stopped            
      networks:
        - traefik-public
        - wiki
volumes:
  db-data:

networks:
  wiki:
  traefik-public:
    external: true

