version: '3.7'

services:
  server:
    image: gitea/gitea:1.14.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=giteasql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea      
    networks:
      - gitea
      - traefik-public
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "2333:22"      
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:        
        - traefik.enable=true        
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public                
        - traefik.http.routers.${NAME}-http.entrypoints=web
        - traefik.http.routers.${NAME}-http.rule=Host(`${NAME}.${DOMAIN}`)
        - traefik.http.services.${NAME}.loadbalancer.server.port=3000
  giteasql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - db:/var/lib/mysql        
volumes:
  gitea:
  db:

networks:
  traefik-public:
    external: true
  gitea:
    external: false    

